# Formatando dados

Precisarei formatar os dados que estavam vazios para aplicar o modelo preditivo.

In [51]:
import pandas as pd

In [52]:
dataset_vazios = pd.read_csv(r'C:\Users\Jose Eduardo\Documents\GitHub\alura_challenge\Dados\dataset_vazios.csv')
dataset_vazios.head(3)

,customerID,Churn,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,...,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,Charges.Monthly,Charges.Total
0,0047-ZHDTW,NaN,Female,0,No,No,11,Yes,Yes,Fiber optic,...,No,No,No,No,No,Month-to-month,Yes,Bank transfer (automatic),79.00,929.3
1,0120-YZLQA,NaN,Male,0,No,No,71,Yes,No,No,...,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,Yes,Credit card (automatic),19.90,1355.1
2,0154-QYHJU,NaN,Male,0,No,No,29,Yes,No,DSL,...,Yes,No,Yes,No,No,One year,Yes,Electronic check,58.75,1696.2

Teremos que fazer todo o tratamento que foi feito anteriormente também para esses dados, primeiro iremos traduzir tudo.

In [53]:
dataset_vazios.columns = ['Identificação do Cliente', 
                          'Churn', 
                          'Sexo', 
                          'Idoso',
                          'Casado', 
                          'Dependentes', 
                          'Meses de Contrato', 
                          'Serviço Telefônico', 
                          'Multiplas Linhas', 
                          'Serviço de Internet',
                          'Proteção Internet',
                          'Backup Online',
                          'Proteção Dispositivo',
                          'Suporte Técnico',
                          'TV a Cabo',
                          'Stremaming Filmes',
                          'Tipo do Contrato',
                          'Fatura Online',
                          'Forma de Pagamento',
                          'Total Gasto Mensal',
                          'Total Gasto Anual'
                         ]

dataset_vazios.replace('No', 'Não', inplace=True)
dataset_vazios.replace('Yes', 'Sim', inplace=True)
dataset_vazios.replace('Fiber optic', 'Fibra ótica', inplace=True)
dataset_vazios.replace('Male', 'Masculino', inplace=True)
dataset_vazios.replace('Female', 'Feminino', inplace=True)
dataset_vazios.replace('No internet service', 'Não tem serviço de internet', inplace=True)
dataset_vazios.replace('Month-to-month', 'Mês a mês', inplace=True)
dataset_vazios.replace('Two year', 'Dois anos', inplace=True)
dataset_vazios.replace('One year', 'Um ano', inplace=True)
dataset_vazios.replace('Electronic check', 'Cheque eletrônico', inplace=True) 
dataset_vazios.replace('Mailed check', 'Cheque', inplace=True)
dataset_vazios.replace('Bank transfer (automatic)', 'Transferência bancária (automática)', inplace=True)
dataset_vazios.replace('Credit card (automatic)', 'Cartão de crédito (automático)', inplace=True) 
dataset_vazios.replace('No phone service', 'Não tem serviço de telefone', inplace=True)

In [54]:
dataset_vazios.head(3)

,Identificação do Cliente,Churn,Sexo,Idoso,Casado,Dependentes,Meses de Contrato,Serviço Telefônico,Multiplas Linhas,Serviço de Internet,...,Backup Online,Proteção Dispositivo,Suporte Técnico,TV a Cabo,Stremaming Filmes,Tipo do Contrato,Fatura Online,Forma de Pagamento,Total Gasto Mensal,Total Gasto Anual
0,0047-ZHDTW,NaN,Feminino,0,Não,Não,11,Sim,Sim,Fibra ótica,...,Não,Não,Não,Não,Não,Mês a mês,Sim,Transferência bancária (automática),79.00,929.3
1,0120-YZLQA,NaN,Masculino,0,Não,Não,71,Sim,Não,Não,...,Não tem serviço de internet,Não tem serviço de internet,Não tem serviço de internet,Não tem serviço de internet,Não tem serviço de internet,Dois anos,Sim,Cartão de crédito (automático),19.90,1355.1
2,0154-QYHJU,NaN,Masculino,0,Não,Não,29,Sim,Não,DSL,...,Sim,Não,Sim,Não,Não,Um ano,Sim,Cheque eletrônico,58.75,1696.2

Aplicando o Encoding nesses dados.

In [55]:
dataset_vazios = dataset_vazios.drop(columns=['Identificação do Cliente', 'Total Gasto Anual'], axis=1)
     
dict_nao = {'Não tem serviço de internet' : 'Não',
           'Não tem serviço de telefone' : 'Não'}
dataset_vazios = dataset_vazios.replace(dict_nao)

colunas_categoricas = ['Serviço de Internet', 'Tipo do Contrato', 'Forma de Pagamento']
dataset_vazios = pd.get_dummies(data=dataset_vazios, columns=colunas_categoricas)

mapa = {'Masculino': 0, 'Feminino': 1}
dataset_vazios.Sexo = dataset_vazios.Sexo.replace(mapa)

mapa = {'Não':0, 'Sim':1}
dataset_vazios = dataset_vazios.replace(mapa)
dataset_vazios.head(3)

,Churn,Sexo,Idoso,Casado,Dependentes,Meses de Contrato,Serviço Telefônico,Multiplas Linhas,Proteção Internet,Backup Online,...,Serviço de Internet_DSL,Serviço de Internet_Fibra ótica,Serviço de Internet_Não,Tipo do Contrato_Dois anos,Tipo do Contrato_Mês a mês,Tipo do Contrato_Um ano,Forma de Pagamento_Cartão de crédito (automático),Forma de Pagamento_Cheque,Forma de Pagamento_Cheque eletrônico,Forma de Pagamento_Transferência bancária (automática)
0,NaN,1,0,0,0,11,1,1,1,0,...,0,1,0,0,1,0,0,0,0,1
1,NaN,0,0,0,0,71,1,0,0,0,...,0,0,1,1,0,0,1,0,0,0
2,NaN,0,0,0,0,29,1,0,1,1,...,1,0,0,0,0,1,0,0,1,0

In [56]:
dataset_vazios.to_csv(r'C:\Users\Jose Eduardo\Documents\GitHub\alura_challenge\Dados\dataset_vazios_formatado.csv', index=False)